import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import React from "react";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/components/providers/NextThemeProvider";
import NextAuthProvider from "@/components/providers/NextAuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <NextAuthProvider>
        <body className={inter.className}>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <div className="min-h-screen flex flex-col justify-center items-center pt-[120px] md:pt-0">
              <div className="w-[95vw] md:w-[60vw] lg:w-[50vw] xl:w-[40vw]">
                {children}
              </div>
            </div>
            <Toaster />
          </ThemeProvider>
        </body>
      </NextAuthProvider>
    </html>
  );
}
